import { Suspense } from "react";
import TicketList from "./TicketList";
import Link from "next/link";

export const metadata = {
  title: "Help Desk App | Tickets",
  description: "Generated by create next app",
};

export default function Tickets() {
  return (
    <main className="max-w-4xl mx-auto p-6">
      {/* Navigation Header */}
      <nav className="sticky top-0 z-10 bg-blue-400/80 backdrop-blur-md text-white font-bold py-4 px-6 rounded-lg shadow-md">
        <div className="text-center">
          <h2 className="text-2xl font-bold">Tickets</h2>
          <p className="text-sm text-gray-200">Currently open tickets</p>
        </div>
      </nav>

      {/* Ticket List Section */}
      <Suspense
        fallback={<p className="text-center mt-6">Loading tickets...</p>}
      >
        <TicketList />
      </Suspense>
      <div className="fixed bottom-4 right-4 mt-6 flex justify-center">
        <Link className="text-blue-500 hover:underline" href={"/"}>Back to HomePage</Link> 
      </div>
    </main>
  );
}
